
export const photos = {
  'Atina Uluslararası Havalimanı (ATH)': 'https://source.unsplash.com/600x360/?airport,athens',
  Atina: 'https://source.unsplash.com/600x360/?athens,acropolis',
  Sounion: 'https://source.unsplash.com/600x360/?sounion,poseidon,temple',
  Delphi: 'https://source.unsplash.com/600x360/?delphi,temple',
  'Korinthos Kanalı': 'https://source.unsplash.com/600x360/?corinth,canal',
  Nafplio: 'https://source.unsplash.com/600x360/?nafplio,port',
  Epidavros: 'https://source.unsplash.com/600x360/?epidavros,theater',
  Mykene: 'https://source.unsplash.com/600x360/?mycenae,ruins',
  Tolo: 'https://source.unsplash.com/600x360/?tolo,beach',
  'Pire Limanı': 'https://source.unsplash.com/600x360/?piraeus,port',
  Hydra: 'https://source.unsplash.com/600x360/?hydra,greece',
  Paros: 'https://source.unsplash.com/600x360/?paros,island',
  Antiparos: 'https://source.unsplash.com/600x360/?antiparos,island',
  Glyfada: 'https://source.unsplash.com/600x360/?glyfada,athens',
  'Paralia Varkiza': 'https://source.unsplash.com/600x360/?varkiza,beach',
  Aegina: 'https://source.unsplash.com/600x360/?aegina,greece',
  Agistri: 'https://source.unsplash.com/600x360/?agistri,greece',
  Marathon: 'https://source.unsplash.com/600x360/?marathon,attica',
  'Schinias Plajı': 'https://source.unsplash.com/600x360/?schinias,beach',
  'Ramnous Ören Yeri': 'https://source.unsplash.com/600x360/?rhamnous,ruins',
  'Rafina Limanı': 'https://source.unsplash.com/600x360/?rafina,port',
  'Marmari (Evia)': 'https://source.unsplash.com/600x360/?marmari,euboea',
  Karystos: 'https://source.unsplash.com/600x360/?karystos,greece',
  'Chalkida (Evia)': 'https://source.unsplash.com/600x360/?chalcis,bridge',
  'Steni Dirfyos': 'https://source.unsplash.com/600x360/?dirfys,forest',
  'Vouliagmeni Gölü': 'https://source.unsplash.com/600x360/?vouliagmeni,lake',
  'Kavouri Plajı': 'https://source.unsplash.com/600x360/?kavouri,beach',
};

export const wikiTitles = {
  'Atina Uluslararası Havalimanı (ATH)': 'Athens_International_Airport',
  Atina: 'Acropolis_of_Athens',
  Sounion: 'Temple_of_Poseidon_at_Sounion',
  Delphi: 'Delphi',
  'Korinthos Kanalı': 'Corinth_Canal',
  Nafplio: 'Nafplio',
  Epidavros: 'Ancient_Theatre_of_Epidaurus',
  Mykene: 'Lion_Gate',
  Tolo: 'Tolo,_Greece',
  'Pire Limanı': 'Port_of_Piraeus',
  Hydra: 'Hydra_(island)',
  Paros: 'Paros',
  Antiparos: 'Antiparos',
  Glyfada: 'Glyfada',
  'Paralia Varkiza': 'Varkiza',
  Aegina: 'Aegina',
  Agistri: 'Agistri',
  Marathon: 'Marathon, Greece',
  'Schinias Plajı': 'Schinias National Park',
  'Ramnous Ören Yeri': 'Rhamnous',
  'Rafina Limanı': 'Rafina',
  'Marmari (Evia)': 'Marmari, Euboea',
  Karystos: 'Karystos',
  'Chalkida (Evia)': 'Chalcis',
  'Steni Dirfyos': 'Steni Dirfyos',
  'Vouliagmeni Gölü': 'Lake Vouliagmeni',
  'Kavouri Plajı': 'Kavouri',
};

export const tips = {
  Atina: {
    about: 'Şehrin tarihi kalbi: Akropolis, Plaka, Monastiraki ve Syntagma çevresi.',
    see: ['Akropolis & Müze', 'Anafiotika sokakları', 'Roma/Antik Agora'],
    eat: ['Ta Karamanlidika tou Fani (meze)', 'Kuzina (manzaralı)', 'Oineas'],
    drink: ['Brettos (Plaka)', 'Six d.o.g.s', 'The Clumsies'],
    localFood: ['Souvlaki', 'Moussaka', 'Spanakopita', 'Loukoumades'],
    localDrink: ['Greek coffee', 'Ouzo', 'Tsipouro'],
  },
  Sounion: {
    about: 'Poseidon Tapınağı ile ünlü, gün batımı efsane.',
    see: ['Poseidon Tapınağı', 'Sahil yolu manzara molaları'],
    eat: ['Lavrio balık tavernaları'],
    drink: ['Sahil kafeleri'],
    localFood: ['Grida', 'Ahtapot ızgara'],
    localDrink: ['Buzlu uzo', 'Beyaz şarap (Attika)'],
  },
  Delphi: {
    about: 'Antik dünyanın kehanet merkezi; dağ manzaraları.',
    see: ['Apollo Tapınağı', 'Stadion', 'Arkeoloji Müzesi'],
    eat: ["Arachova'da taverna"],
    drink: ['Dağ kahvesi & yerel şaraplar'],
    localFood: ['Arachova Formaela peyniri', 'Keçi/kuzu fırın'],
    localDrink: ['Kırmızı şarap', 'Tsipouro'],
  },
  'Korinthos Kanalı': {
    about: "Ege ile İyon'u bağlayan dar kanal.",
    see: ['Köprü üstü fotoğraf'],
    eat: ['Yol üstü atıştırmalık'],
    drink: ['Kısa kahve molası'],
    localFood: ['Korint üzümü', 'Loukaniko'],
    localDrink: ['Bira'],
  },
  Nafplio: {
    about: 'Venedik izleri taşıyan romantik eski şehir.',
    see: ['Palamidi Kalesi', 'Bourtzi'],
    eat: ['Eski şehir tavernaları'],
    drink: ['Liman barları'],
    localFood: ['Gogges', 'Taze deniz ürünleri'],
    localDrink: ['Beyaz şarap', 'Ouzo'],
  },
  Epidavros: {
    about: 'Akustiğiyle ünlü antik tiyatro.',
    see: ['Tiyatro', 'Asklepieion'],
    eat: ['Yol üstü taverna'],
    drink: ['Serin içecek'],
    localFood: ['Zeytinyağlılar', 'Portakallı tatlılar'],
    localDrink: ['Taze portakal suyu'],
  },
  Mykene: {
    about: "Agamemnon'un diyarı; Aslanlı Kapı.",
    see: ['Aslanlı Kapı', 'Kraliyet mezarları'],
    eat: ["Nafplio'da öğle"],
    drink: ['Kahve molası'],
    localFood: ['Gogges', 'Kuzu tandır'],
    localDrink: ['Kırmızı şarap'],
  },
  Tolo: {
    about: 'Sakin kumsallar; deniz günü için ideal.',
    see: ['Plajlar'],
    eat: ['Sahil tavernaları'],
    drink: ['Dondurma & soğuk içecek'],
    localFood: ['Kalamar tava', 'Çipura/Levrek ızgara'],
    localDrink: ['Bira', 'Beyaz şarap'],
  },
  'Pire Limanı': {
    about: 'Adalara feribotların kalktığı ana liman.',
    see: ['Marina Zea'],
    eat: ['Balık restoranları'],
    drink: ['Liman kafeleri'],
    localFood: ['Midye saganaki', 'Gavros tiganito'],
    localDrink: ['Ouzo'],
  },
  Hydra: {
    about: 'Arabasız ada; taş evler ve koylar.',
    see: ['Liman çevresi', 'Kısa yürüyüş rotaları'],
    eat: ['Ada tavernaları'],
    drink: ['Sahil barları'],
    localFood: ['Amygdalota', 'Taze balık'],
    localDrink: ['Buzlu uzo', 'Frappe'],
  },
  Paros: {
    about: 'Plajlar ve Naousa/Parikia kasabaları.',
    see: ['Naousa', 'Kolymbithres'],
    eat: ['Deniz ürünleri'],
    drink: ['Beach barlar'],
    localFood: ['Gouna', 'Xynomizithra'],
    localDrink: ['Souma'],
  },
  Antiparos: {
    about: 'Rahat ada atmosferi.',
    see: ['Antiparos Mağarası', 'Kasaba'],
    eat: ['Meyhaneler'],
    drink: ['Kokteyl barlar'],
    localFood: ['Pasteli', 'Ahtapot ızgara'],
    localDrink: ['Souma', 'Ouzo'],
  },
  Glyfada: {
    about: 'Sahil semti; alışveriş ve kafe kültürü.',
    see: ['Sahil yürüyüşü'],
    eat: ['Kafeler & brunch'],
    drink: ['Kahve barları'],
    localFood: ['Gyros', 'Greek salad'],
    localDrink: ['Frappe'],
  },
  'Paralia Varkiza': {
    about: 'Popüler plaj; deniz ve güneş.',
    see: ['Plaj kulüpleri'],
    eat: ['Sahil tavernaları'],
    drink: ['Soğuk içecekler'],
    localFood: ['Ahtapot ızgara', 'Tarama'],
    localDrink: ['Beyaz şarap', 'Bira'],
  },
  'Atina Uluslararası Havalimanı (ATH)': {
    about: 'Atina ana havalimanı.',
    see: ['Duty free'],
    eat: ['Terminal tavernaları'],
    drink: ['Kafe/barlar'],
    localFood: ['Bougatsa', 'Koulouri'],
    localDrink: ['Frappe'],
  },
  Aegina: {
    about: 'Saronik Adaları’nın en yakını; Aphaia Tapınağı, Perdika ve Aegina fıstığıyla ünlü.',
    see: ['Aphaia Tapınağı', 'Perdika köyü', 'Agia Marina'],
    eat: ['Perdika sahil tavernaları', 'Pistachio’lu tatlılar'],
    drink: ['Liman kafeleri', 'Uzo-meze'],
    localFood: ['Aegina fıstığı (PDO)', 'Taze deniz ürünleri'],
    localDrink: ['Uzo', 'Yunan kahvesi'],
  },
  Agistri: {
    about: 'Küçük, sakin koylarıyla deniz günü için ideal; Aponisos popüler.',
    see: ['Aponisos koyu', 'Skala & Megalochori'],
    eat: ['Ada tavernaları', 'Sahilde meze'],
    drink: ['Sahil barları'],
    localFood: ['Kalamar & ahtapot ızgara'],
    localDrink: ['Bira', 'Uzo'],
  },
  Marathon: {
    about: 'Tarihi Maraton ovası; baraj gölü ve anıt alanı ile bilinir.',
    see: ['Marathon Tümülüsü', 'Marathon Barajı'],
    eat: ['Yerel lokantalar'],
    drink: ['Kahve molası'],
    localFood: ['Köy usulü ızgara etler'],
    localDrink: ['Yunan kahvesi'],
  },
  'Schinias Plajı': {
    about: 'Milli park içinde uzun sahiller; rüzgâr/deniz sporları.',
    see: ['Schinias Milli Parkı', 'Uzun kumsal'],
    eat: ['Beach bar & tavernalar'],
    drink: ['Soğuk içecekler'],
    localFood: ['Balık & deniz ürünleri'],
    localDrink: ['Bira', 'Beyaz şarap'],
  },
  'Ramnous Ören Yeri': {
    about: 'Nemesis Tapınağı kalıntıları ve antik kent; Attika’nın kuzeydoğusunda.',
    see: ['Rhamnous arkeolojik alanı', 'Nemesis Tapınağı'],
    eat: ['Yol üstü taverna'],
    drink: ['Su/soğuk içecek'],
    localFood: ['Zeytinyağlılar'],
    localDrink: ['Yunan kahvesi'],
  },
  'Rafina Limanı': {
    about: 'Evia ve Kiklad hattı feribotları için ikinci büyük Atina limanı.',
    see: ['Liman sahili'],
    eat: ['Balık tavernaları'],
    drink: ['Kafeler'],
    localFood: ['Midye saganaki', 'Gavros tiganito'],
    localDrink: ['Uzo'],
  },
  'Marmari (Evia)': {
    about: 'Sessiz sahil kasabası; Rafina’dan feribotla kolay ulaşım.',
    see: ['Marmari sahil', 'Yakın koylar'],
    eat: ['Sahil tavernaları'],
    drink: ['Kafe & barlar'],
    localFood: ['Taze balık', 'Ahtapot ızgara'],
    localDrink: ['Beyaz şarap'],
  },
  Karystos: {
    about: 'Evia’nın güneyi; Bourtzi kulesi, antik akropolis ve Dimosari vadisi.',
    see: ['Bourtzi', 'Eski akropolis kalıntıları', 'Dimosari vadisi (yürüyüş)'],
    eat: ['Liman balıkçıları'],
    drink: ['Sahil barları'],
    localFood: ['Balık & deniz ürünleri'],
    localDrink: ['Bira', 'Beyaz şarap'],
  },
  'Chalkida (Evia)': {
    about: 'Gelgit benzeri akıntılarıyla meşhur köprü; sahil yürüyüşü.',
    see: ['Euripus boğazı köprüsü', 'Sahil şeridi'],
    eat: ['Şehir tavernaları'],
    drink: ['Kahve & dondurma molası'],
    localFood: ['Izgara balık'],
    localDrink: ['Frappe'],
  },
  'Steni Dirfyos': {
    about: 'Dirfys Dağı eteklerinde serin dağ köyü; yerel taverna kültürü.',
    see: ['Köy merkezi', 'Kısa doğa yürüyüşleri'],
    eat: ['Odun fırınında etler', 'Yerel peynirler'],
    drink: ['Dağ kahvesi'],
    localFood: ['Kuzu fırın', 'Ev yapımı börek'],
    localDrink: ['Şarap'],
  },
  'Vouliagmeni Gölü': {
    about: 'Termal kaynaklı lagün; berrak ve ılık su.',
    see: ['Göl platformları', 'Çevre yürüyüşü'],
    eat: ['Yakın kafeler/tavernalar'],
    drink: ['Soğuk içecekler'],
    localFood: ['Deniz ürünleri meze'],
    localDrink: ['Beyaz şarap'],
  },
  'Kavouri Plajı': {
    about: 'Atina Riviera’nın popüler kumsalı; deniz & gün batımı.',
    see: ['Kavouri sahil hattı'],
    eat: ['Sahil tavernaları'],
    drink: ['Beach bar'],
    localFood: ['Kalamar tava', 'Greek salad'],
    localDrink: ['Bira', 'Frappe'],
  },
};

export const places = {
  'Atina Uluslararası Havalimanı (ATH)': [37.9364, 23.9445],
  Atina: [37.9838, 23.7275],
  Sounion: [37.65, 24.0333],
  Delphi: [38.4828, 22.501],
  'Korinthos Kanalı': [37.928, 22.991],
  Nafplio: [37.567, 22.8053],
  Epidavros: [37.637, 23.1597],
  Mykene: [37.7308, 22.7543],
  Tolo: [37.521, 22.86],
  'Pire Limanı': [37.942, 23.646],
  Hydra: [37.352, 23.475],
  Paros: [37.085, 25.146],
  Antiparos: [37.041, 25.081],
  Glyfada: [37.862, 23.757],
  'Paralia Varkiza': [37.807, 23.786],
  Aegina: [37.745, 23.427],
  Agistri: [37.692, 23.343],
  Marathon: [38.152, 23.962],
  'Schinias Plajı': [38.1485, 24.0355],
  'Ramnous Ören Yeri': [38.148, 24.1015],
  'Rafina Limanı': [38.0238, 24.0056],
  'Marmari (Evia)': [38.041, 24.315],
  Karystos: [38.013, 24.418],
  'Chalkida (Evia)': [38.4639, 23.6025],
  'Steni Dirfyos': [38.5675, 23.8825],
  'Vouliagmeni Gölü': [37.8107, 23.7938],
  'Kavouri Plajı': [37.8126, 23.7689],
};

export const activities = {
  'Atina Uluslararası Havalimanı (ATH)': 'Varış/transfer, check-in & güvenlik/boarding',
  Atina: 'Akropolis, Plaka, Lycabettus',
  Sounion: 'Poseidon Tapınağı gün batımı, plaj',
  Delphi: 'Apollo Tapınağı, müze, Arachova',
  'Korinthos Kanalı': 'Seyir noktası, fotoğraf',
  Nafplio: 'Eski Şehir, Palamidi Kalesi',
  Epidavros: 'Antik tiyatro',
  Mykene: 'Aslanlı Kapı, ören yeri',
  Tolo: 'Plaj ve yüzme',
  'Pire Limanı': 'Feribot/deniz otobüsü kalkış noktası',
  Hydra: 'Arabasız ada — liman, plajlar, taş sokaklar',
  Paros: 'Naousa/Parikia, plajlar; Antiparos geçişi',
  Antiparos: 'Sakin ada havası, kasaba ve mağara',
  Glyfada: 'Sahil semti — kafe/alışveriş',
  'Paralia Varkiza': 'Popüler plaj — deniz günü',
  Aegina: 'Aphaia Tapınağı, Perdika köyü, fıstık (pistachio) ürünleri',
  Agistri: 'Saronik’te deniz günü, Aponisos koyu',
  Marathon: 'Maraton ovası, arkeoloji alanı, baraj gölü',
  'Schinias Plajı': 'Milli park içi uzun sahil, deniz & rüzgâr sporları',
  'Ramnous Ören Yeri': 'Nemesis tapınağı kalıntıları ve antik kent',
  'Rafina Limanı': 'Evia ve Kiklad hattı feribotları',
  'Marmari (Evia)': 'Sessiz sahil kasabası, feribot hattı',
  Karystos: 'Bourtzi, antik akropolis, Dimosari vadisi',
  'Chalkida (Evia)': 'Gelgit benzeri akıntılarıyla meşhur köprü, sahil yürüyüşü',
  'Steni Dirfyos': 'Dirfys eteklerinde serin dağ köyü, taverna',
  'Vouliagmeni Gölü': 'Termal kaynaklı lagün; şifalı su, sakin yüzme',
  'Kavouri Plajı': 'Sahil yürüyüşü ve deniz, Atina Riviera',
};

export const weather = {
  '2025-10-04': {
    ath: { txt: '☀️ 21°/15°' },
    del: { txt: '⛅ 17°/6°' },
    naf: { txt: '🌤 22°/13°' },
    hyd: { txt: '☀️ 17°/13°' },
    par: { txt: '🌤 20°/18°' },
  }, // Sat - Sunny
  '2025-10-05': {
    ath: { txt: '☀️ 22°/17°' },
    del: { txt: '☀️ 19°/11°' },
    naf: { txt: '☀️ 24°/16°' },
    hyd: { txt: '☀️ 17°/15°' },
    par: { txt: '☀️ 21°/18°' },
  }, // Sun - Sunny
  '2025-10-06': {
    ath: { txt: '🌧 23°/17°' },
    del: { txt: '☀️ 18°/9°' },
    naf: { txt: '🌧 22°/14°' },
    hyd: { txt: '☀️ 18°/13°' },
    par: { txt: '☀️ 21°/17°' },
  }, // Mon - Light rain
  '2025-10-07': {
    ath: { txt: '⛅ 19°/13°' },
    del: { txt: '⛅ 15°/6°' },
    naf: { txt: '⛅ 19°/11°' },
    hyd: { txt: '⛅ 16°/11°' },
    par: { txt: '🌦️ 18°/14°' },
  }, // Tue - Partly cloudy
  '2025-10-08': {
    ath: { txt: '⛅ 20°/13°' },
    del: { txt: '🌤 17°/8°' },
    naf: { txt: '🌤 19°/12°' },
    hyd: { txt: '🌤 16°/12°' },
    par: { txt: '⛅ 17°/15°' },
  }, // Wed - Partly cloudy
  '2025-10-09': {
    ath: { txt: '☀️ 21°/14°' },
    del: { txt: '⛅ 18°/8°' },
    naf: { txt: '☀️ 21°/13°' },
    hyd: { txt: '☀️ 17°/13°' },
    par: { txt: '⛅ 20°/15°' },
  }, // Thu - Sunny
  '2025-10-10': {
    ath: { txt: '⛅ 22°/15°' },
    del: { txt: '⛅ 18°/10°' },
    naf: { txt: '☀️ 22°/16°' },
    hyd: { txt: '⛅ 17°/14°' },
    par: { txt: '☀️ 20°/16°' },
  }, // Fri - Mostly sunny
};

export const daysMain = [
  {
    day: '4 Ekim (Cmt) — Varış',
    dateKey: '2025-10-04',
    color: 'red',
    stops: ['Atina Uluslararası Havalimanı (ATH)', 'Atina'],
    plan: [
      '16:35 ZRH kalkış — SWISS LX1840',
      '20:10 ATH varış — pasaport & bagaj',
      '21:00 Otele transfer ve akşam yemeği',
    ],
  },
  {
    day: '5 Ekim (Paz)',
    dateKey: '2025-10-05',
    color: 'orange',
    stops: ['Atina', 'Sounion', 'Atina'],
    plan: [
      '09:00 Akropolis & Müze',
      '12:30 Plaka öğle yemeği',
      '15:00 Vouliagmeni plaj/göl',
      '18:30 Poseidon gün batımı',
      '21:00 Atina dönüş',
    ],
  },
  {
    day: '6 Ekim (Pzt)',
    dateKey: '2025-10-06',
    color: 'green',
    stops: ['Atina', 'Delphi', 'Atina'],
    plan: ["07:30 Delphi'ye çıkış (2.5s)", '10:30 Ören yeri & müze', '13:30 Arachova öğle', "16:00 Atina'ya dönüş"],
  },
  {
    day: '7 Ekim (Sal)',
    dateKey: '2025-10-07',
    color: 'blue',
    stops: ['Atina', 'Korinthos Kanalı', 'Nafplio'],
    plan: ['09:00 Korinthos Kanalı', '11:30 Nafplio eski şehir', '16:00 Palamidi Kalesi', '19:30 Akşam'],
  },
  {
    day: '8 Ekim (Çar)',
    dateKey: '2025-10-08',
    color: 'purple',
    stops: ['Nafplio', 'Epidavros', 'Mykene', 'Nafplio'],
    plan: ['09:30 Epidavros', '12:30 Mykene', '16:30 Nafplio sahil', '19:30 Eski şehir'],
  },
  {
    day: '9 Ekim (Per)',
    dateKey: '2025-10-09',
    color: 'brown',
    stops: ['Nafplio', 'Tolo', 'Nafplio'],
    plan: ['10:00 Tolo plaj', '13:00 Sahil öğle', '15:30 Vivari koyu', '18:30 Dondurma turu'],
  },
  {
    day: '10 Ekim (Cum) — Dönüş',
    dateKey: '2025-10-10',
    color: 'darkcyan',
    stops: ['Nafplio', 'Atina Uluslararası Havalimanı (ATH)'],
    plan: ['09:00 Son kahve', "10:00 ATH'ye yol", '15:00 Check-in', '17:20 ATH→ADB Aegean A3996', '18:20 ADB varış'],
  },
];
export const daysAlt = [
  {
    day: '4 Ekim (Cmt) — Varış',
    dateKey: '2025-10-04',
    color: '#E91E63',
    stops: ['Atina Uluslararası Havalimanı (ATH)', 'Atina'],
    plan: ['16:35 ZRH kalkış — SWISS LX1840', '20:10 ATH varış', '21:00 Otele giriş'],
  },
  {
    day: '5 Ekim (Paz) — Atina Merkez',
    dateKey: '2025-10-05',
    color: '#FF9800',
    stops: ['Atina'],
    plan: ['Akropolis & Müze', 'Plaka/Monastiraki yürüyüş', 'Syntagma nöbet değişimi', 'Akşam Psiri'],
  },
  {
    day: '6 Ekim (Pzt) — Hydra Günü',
    dateKey: '2025-10-06',
    color: '#4CAF50',
    stops: ['Atina', 'Pire Limanı', 'Hydra', 'Pire Limanı', 'Atina'],
    plan: ["Pire'ye geçiş", 'Hydra feribot', 'Ada merkezi & kısa yürüyüş', "Atina'ya dönüş"],
  },
  {
    day: '7 Ekim (Sal) — Güney Kıyı',
    dateKey: '2025-10-07',
    color: '#2196F3',
    stops: ['Atina', 'Glyfada', 'Paralia Varkiza', 'Atina'],
    plan: ['Glyfada kahvaltı', 'Varkiza plaj', 'Akşam merkez'],
  },
  {
    day: '8 Ekim (Çar) — Paros/Antiparos',
    dateKey: '2025-10-08',
    color: '#9C27B0',
    stops: ['Atina', 'Pire Limanı', 'Paros', 'Antiparos', 'Pire Limanı', 'Atina'],
    plan: ['Erken feribot Paros', 'Parikia/Naousa', 'Antiparos kasaba', 'Dönüş/opsiyon konaklama'],
  },
  {
    day: '9 Ekim (Per) — Serbest',
    dateKey: '2025-10-09',
    color: '#795548',
    stops: ['Atina'],
    plan: ['Müzeler / alışveriş / serbest'],
  },
  {
    day: '10 Ekim (Cum) — Dönüş',
    dateKey: '2025-10-10',
    color: '#008B8B',
    stops: ['Atina Uluslararası Havalimanı (ATH)'],
    plan: ['Valiz & check-out', '15:00 Havalimanı', '17:20 ATH→ADB Aegean A3996'],
  },
];

export const daysAlt3 = [
  {
    day: '4 Ekim (Cmt) — Varış & Merkez',
    dateKey: '2025-10-04',
    color: '#2563EB',
    stops: ['Atina'],
    plan: ['20:10 ATH varış → otele geçiş', 'Akşam: Plaka/Monastiraki kısa yürüyüş'],
  },

  {
    day: '5 Ekim (Paz) — Aegina & Agistri (Pire çıkışlı)',
    dateKey: '2025-10-05',
    color: '#0EA5E9',
    stops: ['Atina', 'Pire Limanı', 'Aegina', 'Agistri', 'Pire Limanı', 'Atina'],
    plan: [
      'Sabah: Pire Limanı’na geçiş',
      'Feribot: Aegina (Aphaia Tapınağı / Perdika)',
      'Öğleden sonra: Agistri’de deniz molası',
      'Akşam: Pire → Atina dönüş',
    ],
  },

  {
    day: '6 Ekim (Pzt) — Marathon & Schinias & Rhamnous',
    dateKey: '2025-10-06',
    color: '#10B981',
    stops: ['Atina', 'Marathon', 'Schinias Plajı', 'Ramnous Ören Yeri', 'Atina'],
    plan: [
      'Marathon kasabası ve anıt alan',
      'Schinias Milli Parkı / plaj',
      'Rhamnous antik kenti kalıntıları',
      'Akşam Atina',
    ],
  },

  {
    day: '7 Ekim (Sal) — Evia Güney: Marmari & Karystos',
    dateKey: '2025-10-07',
    color: '#F59E0B',
    stops: ['Atina', 'Rafina Limanı', 'Marmari (Evia)', 'Karystos', 'Marmari (Evia)', 'Atina'],
    plan: [
      'Rafina’dan Marmari’ye feribot',
      'Karystos liman & Bourtzi/akropolis kalıntıları',
      'Dimosari vadisi (kısa yürüyüş) opsiyon',
      'Akşam dönüş',
    ],
  },

  {
    day: '8 Ekim (Çar) — Evia Kuzey: Chalkida & Steni Dirfyos',
    dateKey: '2025-10-08',
    color: '#8B5CF6',
    stops: ['Atina', 'Chalkida (Evia)', 'Steni Dirfyos', 'Atina'],
    plan: [
      'Chalkida deniz üstü köprü ve sahil yürüyüşü',
      'Steni Dirfyos dağ köyü (yerel taverna/kahve)',
      'Akşam Atina',
    ],
  },

  {
    day: '9 Ekim (Per) — Vouliagmeni Gölü & Sahil',
    dateKey: '2025-10-09',
    color: '#EF4444',
    stops: ['Atina', 'Vouliagmeni Gölü', 'Kavouri Plajı', 'Atina'],
    plan: [
      'Sabah: Vouliagmeni Gölü (termal/akvaryum gibi berrak)',
      'Öğle/öğleden sonra: Kavouri plajında deniz',
      'Akşam: Atina merkez',
    ],
  },

  {
    day: '10 Ekim (Cum) — Dönüş',
    dateKey: '2025-10-10',
    color: '#14B8A6',
    stops: ['Atina Uluslararası Havalimanı (ATH)'],
    plan: ['Valiz & check-out', '15:00 Havalimanı', '17:20 ATH → ADB (Aegean A3996)'],
  },
];

export const foodWikiMap = {
  'Souvlaki':'Souvlaki','Moussaka':'Moussaka','Spanakopita':'Spanakopita','Loukoumades':'Loukoumades','Grida':'Gilthead_seabream',
  'Ahtapot ızgara':'Octopus_as_food','Arachova Formaela peyniri':'Formaela','Keçi/kuzu fırın':'Roast_lamb','Korint üzümü':'Zante_currant',
  'Loukaniko':'Loukaniko','Gogges':'Gogges','Kalamar tava':'Calamari','Çipura/Levrek ızgara':'Sea_bream','Midye saganaki':'Saganaki',
  'Gavros tiganito':'Fried_fish','Amygdalota':'Amygdalota','Taze balık':'Fish_as_food','Gouna':'Gouna_(food)','Xynomizithra':'Xynomizithra',
  'Pasteli':'Pasteli','Tarama':'Taramosalata','Gyros':'Gyros','Greek salad':'Greek_salad','Bougatsa':'Bougatsa','Koulouri':'Koulouri',
  'Greek coffee':'Greek_coffee','Ouzo':'Ouzo','Tsipouro':'Tsipouro','Buzlu uzo':'Ouzo','Beyaz şarap (Attika)':'Retsina',
  'Kırmızı şarap':'Wine','Bira':'Beer','Frappe':'Frappé','Souma':'Tsipouro','Taze portakal suyu':'Orange_juice'
};
